# Load a build rule of C++
load("@rules_cc//cc:defs.bzl", "cc_binary")

# Binary rule
cc_binary(
    # Target name, "hello-world"
    name = "hello-world",
    # Source list, relative path to a package directory
    srcs = ["hello-world.cpp"],
)
