load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Rule for ...
# - Downloadng a Bazel repository
# - Decompress it
# - Make its targets available for a binding
http_archive(
    name = "com_google_googletest",
    # Commit id: b796f7d44681514f58a683a3a71ff17c94edb0c1
    url = "https://github.com/google/googletest/archive/b796f7d44681514f58a683a3a71ff17c94edb0c1.zip",
    # Remove prefix from the files
    strip_prefix = "googletest-b796f7d44681514f58a683a3a71ff17c94edb0c1",
)
